#!/bin/sh
#
# print an IMAP envelope

# fields: Number, Interval, Parenthesized, End
N='\([0-9][0-9]*\)'
I='[^{]*'
P="${I}{\([^}]*\)}"
E='[^\n]*'

# font
IT=$(tput smul)
BL=$(tput bold)
RM=$(tput sgr0 | tr -d '\017')

#
# parse fields
#	A. move size at the end
#	B. move flags at the end
#	C. format envelope:
#		1. cut first '*'
#		2. {}\\" -> html entities	chars needed in the following step
#		3. ..."..." -> ...{...}		differentiate open and close quotes
#		4. parse fields			$P is a field
#		5. html entities -> {}"		restore chars
#	D. join formatted envelope with size and flags
#
cut -d' ' -f2- | \
sed '

# move uid at the end
/ENVELOPE/ {
	s,^\(.*\)(UID \([0-9]*\)\(.*\)$,\1\3\nJOINUID:\2,
}

# move size at the end
/RFC822.SIZE/ {
	s,^\(.*\) RFC822.SIZE \([0-9]*\)\(.*\),\1\3\nJOIN'"$BL\2$RM"',
}

# move flags at the end
/FLAGS/ {
	s,^\(.*\) FLAGS (\([^)]*\))\(.*\)$,\1\3\nJOIN\2,
}

# format envelope
/ENVELOPE/ {
	s,{,\&lbrace;,g
	s,},\&rbrace;,g
	s,\\",\&rdquo;,g
	s,\([^"]*\)"\([^"]*\)",\1{\2},g
	'"s,^$N$P$P$P$P$P$E\n,\1: $IT\3$RM\n    $BL\4$RM <\5@\6>\n    \2\n,"'
	s,&[rl]dquo;,",g
	s,&lbrace;,{,g
	s,&rbrace;,},g
}

# join formatted envelope with size and flags
s,\nJOIN,   ,g

# format bodystructure
/BODYSTRUCTURE/ {
	s,^.*BODYSTRUCTURE ,structure: ,
	s,)\r$,,
}

' | \
#
# recode, utf8
#
sed '/?*?[uU][tT][fF]-8?[qQbB]?/ {
	s,_, ,g
	s,?=$,,
	s,?*?[uU][tT][fF]-8?[qQbB]?,,
}' | \
recode -f /qp

