#!/bin/sh
#
# print an IMAP envelope

P='[^{]*{\([^}]*\)}'
IT=$(tput smul)
BL=$(tput bold)
RM=$(tput sgr0 | tr -d '\017')
#IL='\n'

#
# parse fields
#
cut -d' ' -f2- | \
sed -e 's,{,\&lbrace;,g' -e 's,},\&rbrace;,g' -e 's,\\",\&rdquo;,g' | \
sed 's,\([^"]*\)"\([^"]*\)",\1{\2},g' | \
sed "s,^\([0-9][0-9]*\)*$P$P$P$P$P.*,\1: $IT\3$RM\n    $BL\4$RM <\5@\6>\n    \2$IL," | \
sed -e 's,&[rl]dquo;,",g' -e 's,&lbrace;,{,g' -e 's,&rbrace;,},g' | \
#
# recode, utf8
#
sed '/?*?[uU][tT][fF]-8?[qQbB]?/ {
	s,_, ,g
	s,?=$,,
	s,?*?[uU][tT][fF]-8?[qQbB]?,,
}' | \
recode -f /qp

