#!/bin/sh
#
# print an IMAP envelope

# fields: Number, Interval, Size, Parenthesized
N='\([0-9][0-9]*\)'
I='[^{]*'
S="${I}RFC822.SIZE \([0-9][0-9]*\)"
P="${I}{\([^}]*\)}"

# font
IT=$(tput smul)
BL=$(tput bold)
RM=$(tput sgr0 | tr -d '\017')
#IL='\n'

#
# parse fields
#	1. cut first '*'
#	2. {}" -> html entities		chars needed in the following step
#	3. ..."..." -> ...{...}		differentiate open and close quotes
#	4. parse fields			$P is a single field
#	5. html entities -> {}"		restore chars
#
cut -d' ' -f2- | \
sed '
/ENVELOPE/ {
	s,{,\&lbrace;,g
	s,},\&rbrace;,g
	s,\\",\&rdquo;,g
	s,\([^"]*\)"\([^"]*\)",\1{\2},g
	'"s,^$N$S$P$P$P$P$P.*,\1: $IT\4$RM\n    $BL\5$RM <\6@\7>\n    \3$IL   \2,"'
	s,&[rl]dquo;,",g
	s,&lbrace;,{,g
	s,&rbrace;,},g
}
/FLAGS/ {
	s,^.* FLAGS ,flags: ,
	s,)\r$,,
}
/BODYSTRUCTURE/ {
	s,^.*BODYSTRUCTURE ,structure: ,
	s,)\r$,,
} ' | \
#
# recode, utf8
#
sed '/?*?[uU][tT][fF]-8?[qQbB]?/ {
	s,_, ,g
	s,?=$,,
	s,?*?[uU][tT][fF]-8?[qQbB]?,,
}' | \
recode -f /qp

